<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <MonoGamePlatform>Windows</MonoGamePlatform>
	  <OutputPath>$(SolutionDir)\bin\$(Configuration)\mods</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="Engine.Mods.ModAssemblyAttribute"></AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MonoGame.Content.Builder.Task.Compute" Version="3.8.1.2" PrivateAssets="All" />
		<PackageReference Include="Tracy-CSharp" Version="0.11.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\bepuphysics2\BepuPhysics\BepuPhysics.csproj" />
		<ProjectReference Include="..\bepuphysics2\BepuUtilities\BepuUtilities.csproj" />
		<ProjectReference Include="..\BrUtility\BrAssetsManager\BrAssetsManager.csproj" PrivateAssets="All" />
		<ProjectReference Include="..\BrUtility\BrNineSlice\BrNineSlice.csproj" PrivateAssets="All" />
		<ProjectReference Include="..\BrUtility\BrUtility\BrUtility.csproj" PrivateAssets="All" />
		<ProjectReference Include="..\MonoGame\MonoGame.Framework\MonoGame.Framework.WindowsDX.csproj" />
		<ProjectReference Include="..\Engine\Engine.csproj" />
	</ItemGroup>
</Project>
