<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
	<MonoGamePlatform>Windows</MonoGamePlatform>
	<RootNamespace>ViMG</RootNamespace>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<ApplicationIcon>logo.ico</ApplicationIcon>
	<Configurations>Debug;Release;DebugNoTracy</Configurations>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='DebugNoTracy|net8.0-windows|AnyCPU'">
    <DefineConstants>$(DefineConstants);NOTRACY;DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bepuphysics2\**" />
    <Compile Remove="BrUtility\**" />
    <Compile Remove="Engine\**" />
    <Compile Remove="GenerateWorld\**" />
    <Compile Remove="Hexa.NET.ImGui\**" />
    <Compile Remove="LiteNetLib\**" />
    <Compile Remove="MigrationBackup\**" />
    <Compile Remove="ModGameBase\**" />
    <Compile Remove="MonoGame.ImGuiNet\**" />
    <Compile Remove="MonoGame\**" />
    <EmbeddedResource Remove="bepuphysics2\**" />
    <EmbeddedResource Remove="BrUtility\**" />
    <EmbeddedResource Remove="Engine\**" />
    <EmbeddedResource Remove="GenerateWorld\**" />
    <EmbeddedResource Remove="Hexa.NET.ImGui\**" />
    <EmbeddedResource Remove="LiteNetLib\**" />
    <EmbeddedResource Remove="MigrationBackup\**" />
    <EmbeddedResource Remove="ModGameBase\**" />
    <EmbeddedResource Remove="MonoGame.ImGuiNet\**" />
    <EmbeddedResource Remove="MonoGame\**" />
    <None Remove="bepuphysics2\**" />
    <None Remove="BrUtility\**" />
    <None Remove="Engine\**" />
    <None Remove="GenerateWorld\**" />
    <None Remove="Hexa.NET.ImGui\**" />
    <None Remove="LiteNetLib\**" />
    <None Remove="MigrationBackup\**" />
    <None Remove="ModGameBase\**" />
    <None Remove="MonoGame.ImGuiNet\**" />
    <None Remove="MonoGame\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task.Compute" Version="3.8.1.2" PrivateAssets="All" />
    <PackageReference Include="Tracy-CSharp" Version="0.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="bepuphysics2\BepuPhysics\BepuPhysics.csproj" />
    <ProjectReference Include="bepuphysics2\BepuUtilities\BepuUtilities.csproj" />
    <ProjectReference Include="BrUtility\BrAssetsManager\BrAssetsManager.csproj" PrivateAssets="All" />
    <ProjectReference Include="BrUtility\BrNineSlice\BrNineSlice.csproj" PrivateAssets="All" />
    <ProjectReference Include="BrUtility\BrUtility\BrUtility.csproj" PrivateAssets="All" />
    <ProjectReference Include="Engine\Engine.csproj" />
    <ProjectReference Include="MonoGame.ImGuiNet\MonoGame.ImGuiNet\Monogame.ImGuiNet.csproj" />
    <ProjectReference Include="MonoGame\MonoGame.Framework\MonoGame.Framework.WindowsDX.csproj" />
  </ItemGroup>

</Project>
