<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0-windows</TargetFrameworks>
	<MonoGamePlatform>Windows</MonoGamePlatform>
	<RootNamespace>ViMG</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BrUtility\**" />
    <Compile Remove="MonoGame\**" />
    <EmbeddedResource Remove="BrUtility\**" />
    <EmbeddedResource Remove="MonoGame\**" />
    <None Remove="BrUtility\**" />
    <None Remove="MonoGame\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task.Compute" Version="3.8.1.2" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="BrUtility\BrAssetsManager\BrAssetsManager.csproj" PrivateAssets="All" />
    <ProjectReference Include="BrUtility\BrNineSlice\BrNineSlice.csproj" PrivateAssets="All" />
    <ProjectReference Include="BrUtility\BrUtility\BrUtility.csproj" PrivateAssets="All" />
    <ProjectReference Include="MonoGame\MonoGame.Framework\MonoGame.Framework.WindowsDX.csproj" />
  </ItemGroup>

</Project>
